### ISSUE TITLE
Meeting with Jess Results

### ISSUE THREAD

**Issue by allywarner** [allywarner/BrainSegmentation#5]
1. Look into Grey Matter, White Matter, Skull, Sinus and CSF anatomy!
   This is going to help with some decisions about what to cut out or keep.
2. Fix holes in the top part of GM by hand with paint, and using anatomy knowledge
3. Fill holes in WM by hand as well.
4. Check the bottom of grey matter, there is an orange layer of grey matter where I have taken out some of that bottom part. Look up anatomy and figure out what's part of grey matter and what isn't.
5. Clean up the bottom part of grey matter by hand
6. Boolean remove eyes from AND_Skull
7. Try removing the GM from CSF
8. If we can get the skull and the GM done, we can get what's in between for CSF..
9. Can Dilate and Erode GM (make another layer) to get a smoother surface on the inside of the skull.
10. Use the new head
11. When you are removing sinuses by hand from the skull layer, use the mask function to make a sinus layer.

**Comment by andycorb** [comment]
I work with erode and dilate and got the grey matter white matter interface much better. I also did some boolean removes so that grey and white don't overlap in the interior. 

I removed the eyes from the head. 

The CSF is kinda not great. If I remove it from the grey matter or vice versa it looks pretty bad. 

Is the new head labeled as new head? Or is it still just head?
